config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace="core")),
    path('trending/', include('trending.urls', namespace="trending")),
    path('popularity/', include('popularity.urls', namespace="popularity")),
    path('personalized/', include('personalized.urls', namespace="personalized")),
    path('user/preferences/', include('userpref.urls', namespace="userpref")),
]

admin.site.site_header = "SoundSoarAdmin"
admin.site.site_title = "SoundSoarAdmin"
admin.site.index_title = "Welcome to Sound Soar!"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name="home"),
    path('logout/', views.custom_logout, name="custom_logout"),
]

trending/urls.py
from django.urls import path
from . import views

app_name = 'trending'

urlpatterns = [
    path('', views.trending, name='trending'),
    path('search/', views.search_spotify, name='search_spotify'),
    path('filtered/<str:chart_type>/<str:chart_name>/', views.trending_filtered, name='trending_filtered'),
    path('track/<int:pk>/', views.TrackDetailView.as_view(), name='track_detail'),
    path('review/', views.review, name='review'),
    path('model/info/', views.trend_model_info, name='trend_model_info'),
    path('model/info/randomforest/', views.rf_model_info, name='rf_model_info'),
    path('model/info/histgradientboosting/', views.hgb_model_info, name='hgb_model_info'),
    path('model/info/logisticregression/', views.lr_model_info, name='lr_model_info'),
    path('model/info/supportvectormachine/', views.svm_model_info, name='svm_model_info'),
    path('model/info/lineardiscriminantanalysis/', views.lda_model_info, name='lda_model_info'),
    path('model/info/extratrees/', views.extra_model_info, name='extra_model_info'),
    path('model/info/knearestneighbors/', views.knn_model_info, name='knn_model_info'),
]

trending/forms.py
from django import forms
from .models import Sound, SocialMediaPlatform

class TopSoundFilterForm(forms.Form):
    """
    Form for filtering TopSound objects by platform and sentiment.
    """
    platform = forms.ModelChoiceField(
        queryset=SocialMediaPlatform.objects.all(),
        required=False,
        empty_label="All Platforms"
    )
    
    sentiment = forms.ChoiceField(
        choices=[('', 'All Emotions')] + [(code, emotion) for code, emotion in Sound.BASIC_EMOTIONS],
        required=False
    )

    def filter_queryset(self, queryset):
        """
        Filter the queryset based on the form's data.
        """
        platform = self.cleaned_data.get('platform')
        sentiment = self.cleaned_data.get('sentiment')

        if platform:
            queryset = queryset.filter(platform=platform)

        if sentiment:
            queryset = queryset.filter(sentiment=sentiment)

        return queryset

trending/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView
from django.utils import timezone
from .models import Chart, Track, TrackFeatures, TrendModel, FeatureImportance, PopularityHistory, Playlist, StarterScript
from .visualizations import generate_top_ten_track_plot, generate_track_attribute_plot, generate_track_popularity_trend_plot
from .spotify_search import SpotifySearch
from datetime import timedelta

class TrackDetailView(TemplateView):
    template_name = 'trending/track-detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        track_id = self.kwargs['pk']
        track = Track.objects.get(pk=track_id)
        feature = TrackFeatures.objects.get(track=track)

        # Prepare data for the attributes chart
        attributes = {
            'Danceability': track.danceability,
            'Energy': track.energy,
            'Valence': track.valence,
            'Speechiness': track.speechiness,
            'Acousticness': track.acousticness,
            'Instrumentalness': track.instrumentalness,
            'Liveness': track.liveness,
        }

        # Obtain graph obj
        attribute_graph = generate_track_attribute_plot(attributes)

        # Get population data from the last 30 days
        historical_data = feature.get_historical_popularity_tuples()
        dates, popularity_scores = zip(*historical_data) if historical_data else ([], [])

        # Obtain graph obj
        popularity_graph = generate_track_popularity_trend_plot(dates, popularity_scores)

        context['track'] = track
        context['attribute_graph'] = attribute_graph
        context['feature'] = feature
        context['popularity_graph'] = popularity_graph

        return context

def trending(request):
    # Fetch the most recent spotify chart
    most_recent_chart = Chart.objects.filter(chart_type='spotify_playlist').order_by('created_at').first()

    if most_recent_chart:
        # Redirect to the trending_filtered view based on the chart type
        return redirect('trending:trending_filtered', chart_type=most_recent_chart.chart_type, chart_name=most_recent_chart.name)
    else:
        # Handle the case where no playlists are available
        return render(request, 'trending/trending.html', {'charts': [], 'message': 'No playlists available.'})

def trending_filtered(request, chart_type='spotify_playlist', chart_name=''):
    # Fetch the chart based on chart_type and chart_name
    filtered_chart = get_object_or_404(Chart, chart_type=chart_type, name=chart_name)

    # Initialize variables for playlist and track data
    playlist = None
    tracks = None
    track_data = []

    # If chart type is spotify_playlist, get Playlist model data
    if chart_type == 'spotify_playlist':
        playlist = filtered_chart.playlists.first()  # Get the first associated playlist
        if playlist:
            tracks = playlist.tracks.all()

    # If chart type is custom, get CustomPlaylist model data
    elif chart_type == 'custom':
        playlist = filtered_chart.custom_playlists.first()  # Get the first associated custom playlist
        if playlist:
            tracks = playlist.tracks.all()

    # Handle the case where no playlist is available
    if not playlist:
        return render(request, 'trending/trending.html', {'chart': filtered_chart, 'tracks': [], 'message': 'No tracks available for this playlist.'})

    # Fetch track features for the tracks
    track_features = TrackFeatures.objects.filter(track__in=tracks)

    # Create a list of tuples (track, features)
    for track in tracks:
        feature = track_features.filter(track=track).first()
        track_data.append((track, feature))

    # Fetch all charts for the dropdown menu
    all_charts = Chart.objects.all()

    # Generate the Plotly chart (assuming a separate function handles this)
    topten_chart_html = generate_top_ten_track_plot(track_data)

    # Prepare the context
    context = {
        'chart': filtered_chart,
        'track_data': track_data,
        'all_charts': all_charts,
        'topten_chart_html': topten_chart_html,
    }

    return render(request, 'trending/trending.html', context)

def trend_model_info(request):
    active_models = TrendModel.objects.filter(is_active=True).order_by('-created_at')
    inactive_models = TrendModel.objects.filter(is_active=False).order_by('-created_at')
    starter_script = StarterScript.objects.filter(is_active=True)

    # Active Models - Features and CSV
    feature_importance_active = {}
    for active_model in active_models:
        # Fetch the feature importance tuples
        feature_importance_list = FeatureImportance.objects.filter(trend_model=active_model).values_list('feature_name', 'importance')
        # Create a list of formatted strings for feature importance
        feature_importance_active[active_model.id] = [f"{feature[0]} - {feature[1]:.4f}" for feature in feature_importance_list]

    # Inactive Models - Features and CSV
    feature_importance_inactive = {}
    for inactive_model in inactive_models:
        # Similar processing for inactive models
        feature_importance_list = FeatureImportance.objects.filter(trend_model=inactive_model).values_list('feature_name', 'importance')
        feature_importance_inactive[inactive_model.id] = [f"{feature[0]} - {feature[1]:.4f}" for feature in feature_importance_list]

    context = {
        'active_models': active_models,
        'inactive_models': inactive_models,
        'feature_importance_active': feature_importance_active,
        'feature_importance_inactive': feature_importance_inactive,
        'starter_script': starter_script
    }
    return render(request, 'trending/trend-model.html', context)

def review(request):
    # Query for total number of rows for Track
    total_tracks = Track.objects.count()

    # Retrieve all Spotify playlists (assuming you have a Playlist model)
    spotify_playlists = Playlist.objects.all()

    # Retrieve the most recently updated Track and TrackFeatures
    track = Track.objects.order_by('-updated_at').first()
    track_feature = TrackFeatures.objects.order_by('-updated_at').first()

    # Query for popularity history for the last 30 days for the selected track
    if track:
        thirty_days_ago = timezone.now() - timedelta(days=30)
        popularity_history = PopularityHistory.objects.filter(track=track, timestamp__gte=thirty_days_ago)
    else:
        popularity_history = []  # If no track is available, set to an empty list

    # Get the most recent TrendModel based on creation date
    recent_model = TrendModel.objects.latest('created_at')

    # Get feature importances for the most recent model
    feature_importances = FeatureImportance.objects.filter(trend_model=recent_model).values_list('feature_name', 'importance')

    starter_script = StarterScript.objects.filter(is_active=True)

    context = {
        'total_tracks': total_tracks,
        'spotify_playlists': spotify_playlists,
        'track': track,
        'track_feature': track_feature,
        'popularity_history': popularity_history,
        'feature_importances' : feature_importances,
        'starter_script': starter_script
    }
    
    return render(request, 'trending/ready-review.html', context)

def rf_model_info(request):
    models = TrendModel.objects.filter(model_type='RandomForest').order_by('-created_at')
    average_accuracy = TrendModel.get_average_score_for_type(model_type='RandomForest', metric='accuracy')
    average_precision = TrendModel.get_average_score_for_type(model_type='RandomForest', metric='precision')
    average_recall = TrendModel.get_average_score_for_type(model_type='RandomForest', metric='recall')
    average_f1_score = TrendModel.get_average_score_for_type(model_type='RandomForest', metric='f1_score')
    best_params = TrendModel.get_parameters_count_list_for_type(model_type='RandomForest')
    starter_script = StarterScript.objects.filter(is_active=True)
    context = {
        'models': models,
        'average_accuracy': average_accuracy,
        'average_precision': average_precision,
        'average_recall': average_recall,
        'average_f1_score': average_f1_score,
        'best_params': best_params,
        'starter_script': starter_script
    }
    return render(request, 'trending/rf-model.html', context)

def hgb_model_info(request):
    models = TrendModel.objects.filter(model_type='HistGradientBoosting').order_by('-created_at')
    average_accuracy = TrendModel.get_average_score_for_type(model_type='HistGradientBoosting', metric='accuracy')
    average_precision = TrendModel.get_average_score_for_type(model_type='HistGradientBoosting', metric='precision')
    average_recall = TrendModel.get_average_score_for_type(model_type='HistGradientBoosting', metric='recall')
    average_f1_score = TrendModel.get_average_score_for_type(model_type='HistGradientBoosting', metric='f1_score')
    best_params = TrendModel.get_parameters_count_list_for_type(model_type='HistGradientBoosting')
    starter_script = StarterScript.objects.filter(is_active=True)
    context = {
        'models': models,
        'average_accuracy': average_accuracy,
        'average_precision': average_precision,
        'average_recall': average_recall,
        'average_f1_score': average_f1_score,
        'best_params': best_params,
        'starter_script': starter_script
    }
    return render(request, 'trending/hgb-model.html', context)

def lr_model_info(request):
    models = TrendModel.objects.filter(model_type='LogisticRegression').order_by('-created_at')
    average_accuracy = TrendModel.get_average_score_for_type(model_type='LogisticRegression', metric='accuracy')
    average_precision = TrendModel.get_average_score_for_type(model_type='LogisticRegression', metric='precision')

trending/templates/trending/plotly-test.html
<!DOCTYPE html>
<html>
<head>
    <title>Plotly Chart</title>
</head>
<body>
    <h1>Plotly Interactive Chart</h1>
    <!-- Display the chart -->
    <div>
        {{ chart|safe }}
    </div>
</body>
</html>

trending/templates/trending/search.html
{% extends 'core/base.html' %}
{% load static %}
{% load my_filters %}
{% block content %}
<div class="container mt-5">
    <!-- Section 1: Title -->
    <div class="row mb-4">
        <div class="col text-center">
            <h2 class="display-4 fw-bold">Search Results</h2>
            <hr class="mx-auto" style="width: 50%; border-top: 2px solid #333;">
        </div>
    </div>

    <!-- Section 2: Search Bar -->
    <div class="row mb-4">
        <div class="col text-center">
            <form method="GET" action="{% url 'trending:search_spotify' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="query" placeholder="Search for tracks..." required>
                    <button class="btn btn-primary" type="submit" style="background-color: #0077b6; border-color: #0077b6;">Search</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Section 3: Track Table -->
    <h3 class="mb-3">Track List</h3>
    {% if track_data %}
        <div class="table-responsive">
            <table id="trackTable" class="table table-striped" data-toggle="table" data-pagination="true" data-search="false">
                <thead class="table-dark">
                    <tr>
                        <th data-field="order" data-sortable="true">#</th>
                        <th data-field="track_name" data-sortable="true">Track Name</th>
                        <th data-field="artist" data-sortable="true">Artist</th>
                        <th data-field="album" data-sortable="true">Album</th>
                        <th data-field="predicted_trend" data-sortable="true">Predicted Trend</th>
                        <th data-field="popularity" data-sortable="true">Popularity</th>
                        <th data-field="sp_url" data-sortable="false">Spotify Link</th>
                        <th data-field="action" data-sortable="false">Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for track in track_data %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ track.name }}</td>
                            <td>{{ track.artist }}</td>
                            <td>{{ track.album }}</td>
                            <td>{{ track.predicted_trend }}</td>
                            <td>{{ track.current_popularity }}</td>
                            <td>
                                <a href="{{ track.spotify_url }}" class="btn btn-success" target="_blank" style="background-color: #1DB954; border: none; color: white;">
                                    Open Track
                                </a>
                            </td>
                            <td>
                                <button class="btn" style="background-color: #b5c1c7; color: black;" data-bs-toggle="modal" data-bs-target="#trackModal" 
                                    data-name="{{ track.name }}" 
                                    data-artist="{{ track.artist }}" 
                                    data-album="{{ track.album }}" 
                                    data-popularity="{{ track.current_popularity }}"  
                                    data-valence="{{ track.valence }}"
                                    data-tempo="{{ track.tempo }}"
                                    data-speechiness="{{ track.speechiness }}"
                                    data-danceability="{{ track.danceability }}"
                                    data-liveness="{{ track.liveness }}"
                                    data-rf-prediction="{{ track.rf_predicted_trend }}"
                                    data-hgb-prediction="{{ track.hgb_predicted_trend }}"
                                    data-lr-prediction="{{ track.lr_predicted_trend }}"
                                    data-svm-prediction="{{ track.svm_predicted_trend }}"
                                    data-extra-prediction="{{ track.extra_predicted_trend }}"
                                    data-lda-prediction="{{ track.lda_predicted_trend }}"
                                    data-knn-prediction="{{ track.knn_predicted_trend }}"
                                    data-velocity="{{ track.velocity }}"
                                    data-median-popularity="{{ track.median_popularity }}"
                                    data-mean-popularity="{{ track.mean_popularity }}"
                                    data-std-popularity="{{ track.std_popularity }}"
                                    data-retrieval-frequency="{{ track.retrieval_frequency }}"
                                    spotify-url="{{ track.spotify_url }}"
                                    >
                                    View
                                </button>                                 
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">No tracks found for this query.</div>
    {% endif %}
    
    <!-- Track Details Modal -->
    <div class="modal fade" id="trackModal" tabindex="-1" aria-labelledby="trackModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" style="margin: auto; padding-top: 20px; padding-bottom: 20px;">
            <div class="modal-content" style="border-radius: 15px; border: 2px solid #333; background-color: #ffffff;">
                <div class="modal-header" style="background-color: #0077b6;">
                    <h5 class="modal-title text-white" id="trackModalLabel">Track Details</h5>
                    <button type="button" data-bs-dismiss="modal" aria-label="Close" style="background: none; border: none; padding: 0;">
                        <i class="fas fa-times" style="color: black; font-size: 20px;"></i>
                    </button>                 
                </div>
                <div class="modal-body" style="padding: 20px;">

                    <p style="margin-bottom: 10px;"><strong>Track:</strong> <span id="modalTrackName"></span></p>
                    <p style="margin-bottom: 10px;"><strong>Album:</strong> <span id="modalAlbumName"></span></p>
                    <p style="margin-bottom: 10px;"><strong>Artist:</strong> <span id="modalArtistName"></span></p>
                    <p style="margin-bottom: 10px;"><strong>Current Popularity Score:</strong> <span id="modalPopularity"></span></p>
                    <p style="margin-bottom: 10px;"><strong>Track Attributes:</strong></p>
                    <ul>
                        <li>Valence: <span id="modalValence"></span></li>
                        <li>Tempo: <span id="modalTempo"></span></li>
                        <li>Speechiness: <span id="modalSpeechiness"></span></li>
                        <li>Danceability: <span id="modalDanceability"></span></li>
                        <li>Liveness: <span id="modalLiveness"></span></li>
                    </ul>
                    <p style="margin-bottom: 10px;"><strong>Predicted Trends:</strong></p>
                    <ul>
                        <li>Random Forest: <span id="modalRFPrediction"></span></li>
                        <li>Hist Gradient Boosting: <span id="modalHGBPrediction"></span></li>
                        <li>Logistic Regression: <span id="modalLRPrediction"></span></li>
                        <li>SVM: <span id="modalSVMPrediction"></span></li>
                        <li>Extra Trees: <span id="modalExtraPrediction"></span></li>
                        <li>LDA: <span id="modalLDAPrediction"></span></li>
                        <li>KNN: <span id="modalKNNPrediction"></span></li>
                    </ul>
                    <p style="margin-bottom: 10px;"><strong>Trend Popularity History:</strong></p>
                    <ul>
                        <li>Velocity: <span id="modalVelocity"></span></li>
                        <li>Median Popularity: <span id="modalMedianPopularity"></span></li>
                        <li>Mean Popularity: <span id="modalMeanPopularity"></span></li>
                        <li>STD Popularity: <span id="modalStdPopularity"></span></li>
                        <li>retrieval_frequency: <span id="modalRetrievalFrequency"></span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Include jQuery, Bootstrap JS, and Plotly.js -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script>
        // JavaScript to handle modal population
        $('#trackModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var name = button.data('name'); // Extract info from data-* attributes
            var artist = button.data('artist');
            var album = button.data('album');
            var popularity = button.data('popularity'); // Current popularity
            var valence = button.data('valence');
            var tempo = button.data('tempo');
            var speechiness = button.data('speechiness');
            var danceability = button.data('danceability');
            var liveness = button.data('liveness');
            var rf_prediction = button.data('rf-prediction');
            var hgb_prediction = button.data('hgb-prediction');
            var lr_prediction = button.data('lr-prediction');
            var svm_prediction = button.data('svm-prediction');
            var extra_prediction = button.data('extra-prediction');
            var lda_prediction = button.data('lda-prediction');
            var knn_prediction = button.data('knn-prediction');
            var velocity = button.data('velocity');
            var medianPopularity = button.data('median-popularity');
            var meanPopularity = button.data('mean-popularity');
            var stdPopularity = button.data('std-popularity');
            var retrievalFrequency = button.data('retrieval-frequency');

            // Update the modal's content
            var modal = $(this);
            modal.find('#modalTrackName').text(name);
            modal.find('#modalArtistName').text(artist);
            modal.find('#modalAlbumName').text(album);
            modal.find('#modalPopularity').text(popularity);
            modal.find('#modalValence').text(valence);
            modal.find('#modalTempo').text(tempo);
            modal.find('#modalSpeechiness').text(speechiness);
            modal.find('#modalDanceability').text(danceability);
            modal.find('#modalLiveness').text(liveness);
            modal.find('#modalRFPrediction').text(rf_prediction);
            modal.find('#modalHGBPrediction').text(hgb_prediction);
            modal.find('#modalLRPrediction').text(lr_prediction);
            modal.find('#modalSVMPrediction').text(svm_prediction);
            modal.find('#modalExtraPrediction').text(extra_prediction);
            modal.find('#modalLDAPrediction').text(lda_prediction);
            modal.find('#modalKNNPrediction').text(knn_prediction);
            modal.find('#modalVelocity').text(velocity);
            modal.find('#modalMedianPopularity').text(medianPopularity);
            modal.find('#modalMeanPopularity').text(meanPopularity);
            modal.find('#modalStdPopularity').text(stdPopularity);
            modal.find('#modalRetrievalFrequency').text(retrievalFrequency);

        });
    </script>
</div>
{% endblock content %}

trending/templates/trending/trending.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <!-- Section 1: Title -->
    <div class="row mb-4">
        <div class="col text-center">
            <h2 class="display-4 fw-bold">Trending Songs</h2>
            <hr class="mx-auto" style="width: 50%; border-top: 2px solid #333;">
        </div>
    </div>
    <!-- Section 2: Chart Information -->
    <div class="row mb-4">
        <!-- Left Card for Chart Information -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <label for="chart-select" class="form-label">Choose a Chart:</label>
                    <select id="chart-select" class="form-select" onchange="location = this.value;">
                        {% for chart_option in all_charts %}
                            <option value="{% url 'trending:trending_filtered' chart_type=chart_option.chart_type chart_name=chart_option.name %}"
                                {% if chart_option.name == chart.name %} selected {% endif %}>
                                {{ chart_option.name }}
                            </option>
                        {% endfor %}
                    </select>
                    <div class="mt-3">
                        <h6>Chart Information:</h6>
                        <p class="card-text"><strong>Name:</strong> {{ chart.name }}</p>
                        <p class="card-text"><strong>Type:</strong> {{ chart.chart_type }}</p>
                        <p class="card-text"><strong>Description:</strong> {{ chart.description|safe }}</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Area for Top Ten Chart -->
        <div class="col-md-8">
            <div>
                {{ topten_chart_html|safe }}
            </div>
        </div>
    </div>
 
    <!-- Section 3: Track Table -->
    <h3 class="mb-3">Full Track List</h3>
    {% if track_data %}
        <div class="table-responsive">
            <table id="trackTable" 
                class="table table-striped" 
                data-toggle="table" 
                data-pagination="true"
                data-search="true">
                <thead class="table-dark">
                    <tr>
                        <th data-field="order" data-sortable="true">#</th>
                        <th data-field="track_name" data-sortable="true">Track Name</th>
                        <th data-field="artist" data-sortable="true">Artist</th>
                        <th data-field="trend" data-sortable="true">Current Trend</th>
                        <th data-field="trend" data-sortable="true">Predicted Trend</th>
                        <th data-field="action" data-sortable="false">Action</th> <!-- Ensure 'sortable' is false for action -->
                    </tr>
                </thead>
                <tbody>
                    {% for track, feature in track_data %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ track.name }}</td>
                            <td>{{ track.artist }}</td>
                            <td>{% if feature %}{{ feature.trend }}{% else %}N/A{% endif %}</td>
                            <td>{% if feature %}{{ feature.predicted_trend }}{% else %}N/A{% endif %}</td>
                            <td>
                                <a class="btn" href="{% url 'trending:track_detail' track.id %}" style="background-color: #b5c1c7; color: black;">
                                    View Details
                                </a>                                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">No tracks available for this playlist.</div>
    {% endif %}

    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.18.3/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
</div>
{% endblock content %}