config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace="core")),
    path('trending/', include('trending.urls', namespace="trending")),
    path('popularity/', include('popularity.urls', namespace="popularity")),
    path('personalized/', include('personalized.urls', namespace="personalized")),
    path('user/preferences/', include('userpref.urls', namespace="userpref")),
]

admin.site.site_header = "SoundSoarAdmin"
admin.site.site_title = "SoundSoarAdmin"
admin.site.index_title = "Welcome to Sound Soar!"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name="home"),
    path('logout/', views.custom_logout, name="custom_logout"),
]

trending/urls.py
from django.urls import path
from . import views

app_name = 'trending'

urlpatterns = [
    path('', views.trending, name='trending'),
    path('search/', views.search_spotify, name='search_spotify'),
    path('filtered/<str:chart_type>/<str:chart_name>/', views.trending_filtered, name='trending_filtered'),
    path('track/<int:pk>/', views.TrackDetailView.as_view(), name='track_detail'),
    path('review/', views.review, name='review'),
    path('model/info/', views.trend_model_info, name='trend_model_info'),
    path('model/info/randomforest/', views.rf_model_info, name='rf_model_info'),
    path('model/info/histgradientboosting/', views.hgb_model_info, name='hgb_model_info'),
    path('model/info/logisticregression/', views.lr_model_info, name='lr_model_info'),
    path('model/info/supportvectormachine/', views.svm_model_info, name='svm_model_info'),
    path('model/info/lineardiscriminantanalysis/', views.lda_model_info, name='lda_model_info'),
    path('model/info/extratrees/', views.extra_model_info, name='extra_model_info'),
    path('model/info/knearestneighbors/', views.knn_model_info, name='knn_model_info'),
]

userpref/urls.py
from django.urls import path
from . import views

app_name = 'userpref'

urlpatterns = [
    path('', views.preferences, name="preferences"),
]

core/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.shortcuts import redirect, get_object_or_404


def home(request):
    context = {}
    return render(request, 'core/index.html', context)

def custom_logout(request):
    logout(request)
    return redirect('core:home')

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>SoundSoar</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" rel="stylesheet" />
        <!--STYLE-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet"/>
    </head>
    <body>
        <!-- Invisible anchor at the top the page -->
        <div id="top"></div>
        <!-- Navbar -->
        <header>
            <div class="container-fluid">
                <!-- Logo and Name -->
                <div class="nav-header">
                    <div class="nav-info">
                        <img src="{% static 'core/img/logo.png' %}" alt="SoundSoar-Logo" />
                        <div class="nav-text-content">
                            <h1>Sound Soar</h1>
                        </div>
                    </div>
                </div>
                <!-- Account Icon and Modal Trigger -->
                <div class="item-container">
                    <!--<div class="item-icon"> -->
                    <!--    <a href="{% url 'userpref:preferences' %}"> -->
                    <!--        <i class="fa-solid fa-user"></i> -->
                    <!--    </a>-->
                    <!--</div>-->
                    <div class="mobile-toggler">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#navbModal">
                            <i class="fa-solid fa-bars"></i>
                        </a>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="navbModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <!-- Modal Header -->
                            <div class="modal-header">
                                <div class="modal-info">
                                    <img src="{% static 'core/img/logo.png' %}" alt="SoundSoar-Logo" />
                                    <div class="text-content">
                                        <h1>Sound Soar</h1>
                                    </div>
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                    <i class="fa-solid fa-xmark"></i>
                                </button>
                            </div>
                            <!-- Modal Body -->
                            <div class="modal-body">
                                <div class="modal-line">
                                    <i class="fa-solid fa-house"></i>
                                    <a href="{% url 'core:home' %}">Home</a>
                                </div>
                                <div class="modal-line">
                                    <i class="fa-solid fa-chart-simple"></i>
                                    <a href="{% url 'trending:trending' %}">Trending Songs</a>
                                </div>
                                <div class="modal-line">
                                    <i class="fa-solid fa-lightbulb"></i>
                                    <a href="https://soundsoar.com/trending/filtered/custom/SoundSoar%20Suggestions/">Suggested Songs</a>
                                </div>
                                <!--<div class="modal-line"> -->
                                <!--    <i class="fa-solid fa-user"></i> -->
                                <!--    <a href="{% url 'userpref:preferences' %}">Account Settings</a> -->
                                <!--</div> -->
                                <br>
                                <div class="modal-line">
                                    <i class="fa-solid fa-database"></i>
                                    <a href="{% url 'trending:trend_model_info' %}">Trend Model History</a>
                                </div>
                                <div class="modal-line">
                                    <i class="fa-solid fa-circle-info"></i>
                                    <a href="{% url 'trending:review' %}">Trend Insights & Review</a>
                                </div>
                                <br>
                                <div class="modal-line">
                                    <i class="fa-solid fa-video"></i>
                                    <a href="https://www.youtube.com/watch?v=z6fxp4pTHbg">Demo Video</a>
                                </div>
                                <br><br>
                                <!-- LOGOUT BUTTON -->
                                    <!--{% if user.is_authenticated %} -->
                                    <!-- Sign-out button for logged-in users -->
                                    <!--<li> -->
                                     <!--   <a href="{% url 'core:custom_logout' %}" style="background-color: #0077b6; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold; transition: background-color 0.3s ease;">-->
                                      <!--      Sign Out-->
                                      <!--  </a>-->
                                   <!-- </li>-->
                                   <!-- {% else %}-->
                                    <!-- Sign-in button for guests -->
                                    <!--<li>-->
                                   <!--     <a href="{% url 'trending:trending' %}" style="background-color: #0077b6; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold; transition: background-color 0.3s ease;">-->
                                    <!--        Sign In-->
                                   <!--     </a>-->
                                   <!-- </li>-->
                                   <!-- {% endif %} -->
                            </div>           
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>    
        <!-- --------------------------------------------------------------------------------------------------------------------------- -->
        <!-- Main -->
        <main>
            <!-- --------------------------------------------------------------------------------------------------------------------------- -->
            {% block content %} 

            {% endblock content %}
            <!-- --------------------------------------------------------------------------------------------------------------------------- -->
            <br><br><br>
            <!-- Go To Top Button -->
        <!-- G    <a href="#top" id="goTop">Back to Top</a> -->
        </main>
        <!-- --------------------------------------------------------------------------------------------------------------------------- -->
        <!-- Footer -->
        <footer class="bg-dark py-5 mt-5">
            <div class="container text-light text-center">
                <p class="display-5 mb-3">SoundSoar</p>
                <small class="text-white-50">
                    Full Sail University Capstone Project.<br />
                    Designed and developed by Victoria Grasso.
                </small>
            </div>
        </footer>        
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<!--STYLE-->
<link href="{% static 'core/css/index.css' %}" rel="stylesheet"/>
<!-- Hero Section -->
<div class="hero-container">
    <img src="{% static 'core/img/banner.png' %}" alt="Banner" class="hero-banner">
    <div class="hero-content">
        <h1 class="display-4">Welcome to Sound Soar!</h1>
        <p class="lead">Explore and forecast the hottest tracks on Spotify using SoundSoar's cutting-edge trend analysis capabilities.</p>
        <a href="{% url 'trending:trending' %}" class="btn btn-light btn-lg">Explore Trending Songs</a>
    </div>   
</div>
<!-- Search Section -->
<div class="search-section">
    <h2 class="search-title">Search for a Song</h2>
    <div class="search-container">
        <form method="GET" action="{% url 'trending:search_spotify' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="query" placeholder="Search for tracks..." required>
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}